spring:
  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2
  datasource:
    #    url: jdbc:h2:mem:test
    url: ${HR_DATABASE_URL}
    username: ${HR_DATABASE_USERNAME}
    password: ${HR_DATABASE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      data-locations: classpath*:db/h2/data.sql

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
        web:
          reactive:
            function:
              client: DEBUG

server:
  servlet:
    encoding:
      force-response: true

# Arirang Secret key
infrastructure:
  arirang:
    service-key: ${ENCODED_ARIRANG_SERVICE_KEY}